### ISSUE TITLE
P2p code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/members-only#1]
Please leave some comments.

**Comment by rammazzoti2000** [comment]
Hey @nyatindopatrick, good job this far, as for the validation, you should't get an error there, try to remove length from text validation and see if it works.
As for now, there is no real issue in this project, everything seems alright :rocket:

**Comment by patriciachrysy** [comment]
Good job @nyatindopatrick , authentication with sorcery is a great time saving, but i thought that we are supposed to do this project with device...Maybe I'm wrong. Anyway, your validations on post model looks fine for me.

**Comment by dili021** [comment]
Nicely done so far. Like the styling :)
